### ISSUE TITLE
Add code of conduct 

### ISSUE THREAD

**Issue by SheepReaper** [automate-lfs/jhalfs#3]
It goes in the repo root and named CODE_OF_CONDUCT.md

Maybe use the sample one: [Here](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)

**Comment by pierre-labastie** [comment]
I like the sample you propose. Can you take care of that @bryan5989  (tentatively assigning to you)?

**Comment by SheepReaper** [comment]
Will do
