### ISSUE TITLE
Add Repository templates

### ISSUE THREAD

**Issue by SheepReaper** [automate-lfs/jhalfs#5]
Create the following templates:
- [x] Issue - Bug
- [x] Issue - Question
- [x] Issue - (New) Feature Request
- [x] Pull Request (For contributions)

Proposed changes in #12 

Additional items to complete:
- [ ] Accept philschatz/project-bot installation (enables new issues to be auto-assigned to projects)
- [ ] Review proposed templates for accepted verbiage.

**Comment by SheepReaper** [comment]
The issue templates are also needed for the bugtracker triage automation. The Template for "Bug" can include assigning to Bug tracker project (which itself has automation), otherwise GitHub does not natively support designating a "default" project or making "all new issues" without a project auto-assign themselves to bug tracker.

Just trying to eliminate the need to micro-manage the issues list.

**Comment by pierre-labastie** [comment]
I'm new to all this... What is this "bug tracker project" you have mentioned ? I understand it may add something to the issue tracker. Maybe you could point me to some example? (I feel really dummy)

**Comment by SheepReaper** [comment]
So Github issues... by themselves they are incredibly versatile. If you
master all of the markdown shorthand and keywords for issue titles, you
already get automatic tracking of issues fixed and when using milestones,
you can automatically generate release notes with this information ref:
https://guides.github.com/features/issues/

Now, with Github projects, you get even more automation. When you, as a
contributor, add a new issue, you can optionally tag it to a project. If
you do, for example, if the new issue is a bug, assign it to the bug
tracker project, anyone who is set to receive notifications for that
project, will be notified of a new bug. The issue is added to the first
column. Any project member can then take or assign the bug, which then
moves it into in progress. If you then reference this issue from a commit,
with either closes or fixes keyword in the title, it will close the issue,
and move it to complete.

Projects allow you to assign different team members or allow team members
to join the projects they want to track.

The bug tracker is just a common example of a use for the Github projects
with automation but the projects can be used for feature progress tracking
with deadlines and milestone readiness and other purposes. Se the link
above for examples.

By default, non-members cannot assign a new issue to a project upon
creation. However, Issue templates allow you to assign projects, tags, and
others via the template.

The user sees: here's how you fill out this bug report. On creation, the
template auto assigns to the bug tracker project.

For a pull request template, it might assign to a different project where
we want to review code before committing. Code review notifications can be
automated as well.

**Comment by pierre-labastie** [comment]
@bryan5989, we could maybe first make the bug template (reason: I have a bug to report, and I could try the template). Would you do it, or do I assign this to myself?

**Comment by SheepReaper** [comment]
Let's make it a race, I will try and do it by this afternoon (EDT), but if
you beat me to it, I won't be upset.

**Comment by pierre-labastie** [comment]
Well, i'm not sure whether we can find an already made template, or we have to write one ourselves (in both cases, you know better than I do).

**Comment by SheepReaper** [comment]
make sure one of you accepts the philschatz/project-bot installation request.

That will handle auto assigning bugs and questions to their appropriate projects (Bug tracker and QnA)

**Comment by SheepReaper** [comment]
#5 OP updated, proposed changes: #12

**Comment by pierre-labastie** [comment]
> make sure one of you accepts the philschatz/project-bot installation request.
> 
> That will handle auto assigning bugs and questions to their appropriate projects (Bug tracker and QnA)

Done. Hope the settings are OK.
